spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/share-handong?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    url: jdbc:mysql://b1f09a1440a512:94a88b05@us-cdbr-east-04.cleardb.com/heroku_7cb53baabdefd41?reconnect=true
#    username: root
#    password: qwerasdf
    username: b1f09a1440a512
    password: 94a88b05

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
#  address: localhost
  port: 8080